### ISSUE TITLE
vite-plugin uploads sourcemaps when building for development

### ISSUE THREAD

**Issue by playaz87** [getsentry/sentry-javascript-bundler-plugins#528] opened 2024-04-24 06:01 UTC
### Environment

@sentry/react: 7.112.1
@sentry/vite-plugin: 2.16.1
vite: 5.1.4
react: 18.2.0

The [documentation](https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/vite/) says: 

> The Sentry Vite plugin doesn't upload source maps in watch-mode/development-mode. We recommend running a production build to test your configuration.

However when I build with `tsc && vite build --mode development` source maps are generated and uploaded.

**Comment by lforst** [comment] 2024-04-24 07:39
Thanks! Closing because it is a duplicate of: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/520

**Closed by lforst** 2024-04-24 07:39 UTC
Labels: Waiting for: Product Owner
