### ISSUE TITLE
Automatic Release Numbering / Error correlation doesn't appear to work 

### ISSUE THREAD

**Issue by quickstark** [getsentry/sentry-javascript-bundler-plugins#182] opened 2023-03-08 20:37 UTC
### Environment

"@sentry/react": "^7.38.0",
"@sentry/tracing": "^7.38.0",
"@sentry/vite-plugin": "^0.4.0",

### Steps to Reproduce

1. Don't specify a release param in vite.confit or Sentry.init
2. Build
3. Run build preview
4. Generate an Error
5. Check Sentry Issue for release value / associated sourcemap

### Expected Result

In the absence of any other release information, the Git commit hash gets automatically set as the release and correlated to any Errors within the release

### Actual Result

Git commit hash gets used, a Sentry release is created, sourcemaps are uploaded, but the Error doesn't contain the corresponding release tag.

It works as expected if you specify the release param as part of vite.config and Sentry.init.

![CleanShot 2023-03-08 at 10 48 35](https://user-images.githubusercontent.com/17515078/223843975-604b0954-b596-43ae-8fef-3ac44a7f5b75.png)

**Comment by lforst** [comment] 2023-03-09 06:39
hi what framework are you using?

**Comment by smeubank** [comment] 2023-03-10 12:49
@HazAT moving this to backlog

vite is by far our most popular plugin here, should prio it

**Comment by Lms24** [comment] 2023-03-20 09:45
Hi @quickstark thanks for reporting this! 

Can you share your `Sentry.init` config as well as your vite config with the options you pass to our Vite plugin? Also, if you can, please provide a minimal reproduction (e.g. stackblitz or a git repo) so that we can debug this. 

Thanks a lot :)

**Comment by hakubo** [comment] 2023-03-21 11:39
From what I'm able to notice is that SENTRY_RELEASE is not being injected.

Downgrading to 0.3 does help.

**Comment by hakubo** [comment] 2023-03-21 11:43
passing
```
injectReleasesMap: true
```

to configuration seems to help

**Comment by hakubo** [comment] 2023-03-21 12:15
Looks like there was a change, but not documented well: https://github.com/getsentry/sentry-javascript-bundler-plugins/commit/6ca81b8b0657bb210623e0dab8f8eefaec7e5eb6

**Comment by hakubo** [comment] 2023-03-21 12:16
Documentation stills states that: 'By default, the release will be injected into all modules - however, bundlers will include the injected release code only once per entrypoint. If release injection should be disabled, provide an empty array here.'

**Comment by hakubo** [comment] 2023-03-21 12:43
I susspect the issue is here: 

resolveId(id, importer, { isEntry }) {

https://github.com/getsentry/sentry-javascript-bundler-plugins/commit/6ca81b8b0657bb210623e0dab8f8eefaec7e5eb6#diff-4cc9f0580cf306df7930b52b4003992e03eef9a6442047a7d44a379c1e1ab0b7L165

in vite, index.html is entry point. To this would be false for apps, meaning you wont inject the globals to any file.

**Comment by lforst** [comment] 2023-03-22 10:42
@hakubo this is a known issue. I have a fix in mind. In the meanwhile you can do what we recommended here: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/180

**Closed** 2023-03-30 05:28 UTC
Labels: bug
