### ISSUE TITLE
ReferenceError: require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by polvallverdu** [getsentry/sentry-javascript-bundler-plugins#457] opened 2024-01-06 10:19 UTC
### Environment

What version are you running? Etc.

I'm running node 20 with SvelteKit. This happens inside my Docker container (node:20), and in my Windows PC.

### Steps to Reproduce

1. Create a SvelteKit project
2. Use Sentry
3. pnpm build
4. node build (to serve)

### Expected Result

Serve the bundled js with a node http server.

### Actual Result

```
file:///D:/vscode/xxxx/build/server/chunks/index.server---lhU4i_.js:91216
var releaseInjectionFilePath = require.resolve("@sentry/bundler-plugin-core/sentry-release-injection-file");
                               ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'D:\vscode\xxxx\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///D:/vscode/xxxx/build/server/chunks/index.server---lhU4i_.js:91216:32
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async Server.init (file:///D:/vscode/xxxx/build/server/chunks/index-cn-9jQeW.js:3903:24)
    at async file:///D:/vscode/xxxx/build/handler.js:1130:1

Node.js v20.9.0
```

**Comment by Lms24** [comment] 2024-01-08 08:43
Hi @polvallverdu thanks for writing in! Would you mind sharing a minimal reproduction example (e.g. as a github repo) so we can debug this? Haven't seen this error before. Do you use other Vite plugins in your Sveltekit app or any special vite or svelte config that is not present by default? Thanks!

**Comment by polvallverdu** [comment] 2024-01-08 11:27
Non other than the one included with sveltekit. I'm using the node adapter (SSR). Here's a barebones repo I've created to actually reproduce the issue. When running pnpm build && pnpm preview it works, but when building the container and running it from the nodejs http server, it just doesn't (running `node build` locally also makes the error happen). 

https://github.com/polvallverdu/sentry-svelte-test

```
2024-01-08 12:24:11 node:internal/modules/esm/resolve:844
2024-01-08 12:24:11   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
2024-01-08 12:24:11         ^
2024-01-08 12:24:11 
2024-01-08 12:24:11 Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sentry/sveltekit' imported from /app/build/server/chunks/hooks.server-GtpXkpQ4.js
2024-01-08 12:24:11     at packageResolve (node:internal/modules/esm/resolve:844:9)
2024-01-08 12:24:11     at moduleResolve (node:internal/modules/esm/resolve:901:20)
2024-01-08 12:24:11     at defaultResolve (node:internal/modules/esm/resolve:1121:11)
2024-01-08 12:24:11     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
2024-01-08 12:24:11     at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
2024-01-08 12:24:11     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
2024-01-08 12:24:11     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
2024-01-08 12:24:11     at link (node:internal/modules/esm/module_job:84:36) {
2024-01-08 12:24:11   code: 'ERR_MODULE_NOT_FOUND'
2024-01-08 12:24:11 }
2024-01-08 12:24:11 
2024-01-08 12:24:11 Node.js v20.10.0
```

**Comment by Lms24** [comment] 2024-01-09 09:29
@polvallverdu I found the problem: `@sentry/sveltekit` was added to your `devDependencies` instead of `dependencies`. This will cause Vite and pnpm to treat the package differently, producing errors like the one you encountered. 

If I move the package to `dependencies` in `package.json`, re-install and build with pnpm and run with `node build`, everything works again. 

I'm gonna close this issue as I'm fairly certain that this is the cause for the reported error. Please let me know if the issue still persists on your end. 

Our of curioisity: Did you install the SDK manually or via the wizard? If the wizard added the SDK to `devDependencies` then there's a bug in the wizard we should fix.

**Closed by Lms24** 2024-01-09 09:29 UTC
Labels: Waiting for: Product Owner

**Comment by polvallverdu** [comment] 2024-01-09 09:51
That was it! Thank you so much. Have a great day

**Comment by andreineamtu** [comment] 2024-01-29 14:27
Thank you for the suggestion. It worked for me too, just that in my case I was using another dependency that I installed in devDepencies.

**Comment by bfontaine** [comment] 2025-07-17 16:01
@andreineamtu how did you find out what other dependency was causing the issue? I have `@sentry/sveltekit` and `@sentry/vite-plugin` in my `dependencies` (not `devDependencies`), but I have a similar issue:

```
        ReferenceError: require is not defined in ES module scope, you can use import instead
        This file is being treated as an ES module because it has a '.js' file extension and '/myapp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
            at ExportsCache.has (file:///myapp/build/server/chunks/hooks.server-DbrNhrJ6.js:23695:20)
            at Module.patchedRequire (file:///myapp/build/server/chunks/hooks.server-DbrNhrJ6.js:23823:22)
            at Hook._require.Module.require (file:///myapp/build/server/chunks/hooks.server-DbrNhrJ6.js:23762:28)
            at require (node:internal/modules/helpers:182:18)
            at Object.<anonymous> (/myapp/node_modules/@elastic/elasticsearch/index.js:35:5)
            at Module._compile (node:internal/modules/cjs/loader:1529:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
            at Module.load (node:internal/modules/cjs/loader:1275:32)
            at Module._load (node:internal/modules/cjs/loader:1096:12)
            at cjsLoader (node:internal/modules/esm/translators:298:15)
```

I have almost nothing in my `devDependencies`.
