### ISSUE TITLE
error: release not found

### ISSUE THREAD

**Issue by ggyuer** [getsentry/sentry-javascript-bundler-plugins#392] opened 2023-09-01 07:55 UTC
### Environment
 
version 2.7.0 

### Steps to Reproduce

1.  Compilation error => error: release not found
2.  But I gave release.name
3.   
<img width="477" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/20310848/b6b99e18-7432-4460-9a34-7d856965c9f1">
<img width="474" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/20310848/882b6143-5031-406f-b763-4d4ab81c177c">

I tried to directly change the compilation source code, but the same issue still exists
<img width="512" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/20310848/cc350181-9792-48d9-9602-d489d257709e">

Why?

**Comment by lforst** [comment] 2023-09-01 08:00
Hi, this is a duplicate of https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/289

**Closed by lforst** 2023-09-01 08:00 UTC
Labels: Waiting for: Product Owner

**Comment by ggyuer** [comment] 2023-09-01 08:16
self hosted v22.11.0 
sentryWebpackPlugin
Is there any way? Downgraded version? 2.7.0
