### ISSUE TITLE
Service Worker "import sentry-release-injection" error when sourcemapping for Sentry (Vite plugin)

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-javascript-bundler-plugins#460] opened 2024-01-10 11:27 UTC
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/vue

### SDK Version

7.91.0

### Framework Version

Vue 3.2.0

### SDK Setup

```
sentryVitePlugin({
        org: 'xxxxx',
        project: 'xxxxxx',
        release: {
          name: 'xxxxxx'
        }
}),
VitePWA({
        registerType: 'prompt',
         devOptions: {
            enabled: true
          },
          workbox: {
            globPatterns: ['**/*.{js,css,html,ico,png,jpg,jpeg,svg}']
          },
          manifest: {}
  })
})
```

### Steps to Reproduce

1. Add sentryVitePlugin and VitePWA plugins on vite.config
2. yarn dev

### Expected Result

Not having an import sourcemap error

### Actual Result

Console:
Uncaught SyntaxError: Cannot use import statement outside a module (at dev-sw.js?dev-sw:99:2)

File error:

```
workbox.precache({})
//# sourceMappingURL=sw.js.map

;import "/@id/__x00__sentry-release-injection-file";
//# sourceMappingURL=xxx
```

**Comment by houxg** [comment] 2024-01-23 13:27
I also encountered this problem and here is a simple reproduction:

1. create an vue3 project and set up sentry vite plugin
2. create `env.js` file in project dir, with content`window.appEnv={apiHost: "http://localhost:8100"}`
3. reference this js file in head of `index.html`
```
<head>
  ...
  <script type="text/javascript">
    document.write("<script src='/env.js?v=" + new Date().getTime() + "'><\/script>")
  </script>
</head>
```
4. `npm run dev` and check the browser, BANG!

**Comment by lforst** [comment] 2024-01-25 11:58
@houxg What do you mean exactly by `create a vue3 project`? Would you mind giving a bit more concrete instructions? Then we can debug more effectively. Thank you!

**Comment by houxg** [comment] 2024-01-28 13:56
> @houxg What do you mean exactly by `create a vue3 project`? Would you mind giving a bit more concrete instructions? Then we can debug more effectively. Thank you!

create a simple vue3 project by vite, and setup sentry-vite-plugin.

**Comment by MaxWeisen** [comment] 2024-04-25 15:37
I am also experiencing this same error. Here are the packages and versions I am working with: 
```
nuxt: 3.10.3
vue: 3.4.19
@vite-pwa/nuxt: 0.6.0
@sentry/vue: 5.110.0
@sentry/vite-plugin: 2.16.1
```
Any tips on how to fix this or is Sentry and vite-pwa not able to work together at this time?

**Comment by lforst** [comment] 2024-04-26 08:41
I haven't tried out vite-pwa in combination with the plugin. If someone provides a minimal reproduction example I can take a look. Otherwise we will look at this when we have some spare cycles which may take a while.

**Comment by MaxWeisen** [comment] 2024-04-26 15:55
@lforst Here is a minimal reproduction. I have some instructions on what I did to reproduce the issue in the readme.

https://github.com/MaxWeisen/vite-pwa-sentry-plugin-issue

Thank you!

**Comment by userquin** [comment] 2024-04-26 20:48
This is a problem in both, workbox-build and sentry when using `generateSW` strategy:
- you cannot use type module in non chromium based browsers when registering the sw
- generateSW in workbox-build node module will use `importScripts` when generating the service worker

We cannot use vite-pwa-plugin and sentry in dev server even when registering the service worker with type module.

The workaround is using a custom service worker: in this case, `vite-plugin-pwa` will use custom Vite build to build the service worker: in dev server, Vite will just remove ts annotations; in build mode, we don't have any problem since `vite-plugin-pwa` will not use the plugins in the main build and so sentry will not be in the sw build (you can include sentry plugin in the custom build, Vite will inline sentry import).

Check from this comment and next ones: https://github.com/vite-pwa/nuxt/issues/132#issuecomment-2079951086.

Here a working example in dev server and build here  https://github.com/userquin/vite-pwa-sentry-plugin-issue-120/tree/inject-manifest (inject-manifest branch)

**Comment by mydea** [comment] 2024-04-30 11:05
I am not an expert in this overall, but could a solution also be to just not run the sentryVitePlugin in dev mode at all? IMHO you probably don't need it in dev mode?

**Comment by userquin** [comment] 2024-04-30 11:13
@mydea the problem is about testing the sw and the pwa web manifest, sentry should have a way to exclude some assets, rn any asset with `js/ts/jsx/tsx/mjs` extension being intercepted by the sentry plugin (transform hook), the pwa plugin serving dev sw using `dev-sw.js?dev-sw`: 
- pwa plugin: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/constants.ts#L33 and 
- sentry plugin: https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/bundler-plugin-core/src/index.ts#L404-L410

**Comment by mydea** [comment] 2024-04-30 11:15
Hmm, I guess we could add some kind of `ignore` config to skip certain file globs - would that fix your problem? 🤔

**Comment by userquin** [comment] 2024-04-30 11:16
EDIT: or just exclude the sentry plugin in dev, it is easy, just adding apply: 'build' when exposing the unplugin plugin for vite.

**Comment by mydea** [comment] 2024-04-30 11:20
I think we are unlikely to do this in the plugi

> EDIT: or just exclude the sentry plugin in dev, it is easy, just adding `apply: 'build'` when exposing the unplugin plugin for vite.

I think we are unlikely to do that, if you want this you can simply skip adding the plugin in dev yourself, I guess? Or am I missing something there?

I think having an option to ignore certain files for sourcemaps injection is not unreasonable 🤔 I'll wait for @Lms24 & @lforst to chime in as they know more about the deeper internals of the bundler plugins, though.

**Comment by lforst** [comment] 2024-05-02 12:13
@userquin I still firmly believe this is an issue with `workbox` or `VitePWA`. I think they are externalizing our injected module, which I don't think is correct of them to do. This requires an upstream fix. Would you mind opening an issue in their repositories? Feel free to ping us there and we can provide more context and info to the maintainers.

**Comment by lforst** [comment] 2024-05-02 12:36
If the Sentry vite plugin causes issues you could always use Sentry CLI to inject debug IDs and upload sourcemaps: https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/

Currently, resolving this issue is not a priority for us, since Sentry CLI should work fine as a workaround. If you are down for it you could open a PR with a fix (if you have one in mind). Otherwise, I will backlog this for now.

**Comment by acaldas** [comment] 2024-09-04 18:02
I/m using `@sentry/vite-plugin` and it was adding this import to my service worker.
Fixed it by setting `release.inject` to false.
Will this cause any issues in the error reporting?

**Comment by Lms24** [comment] 2024-09-05 08:07
Hi, if you set `release` in your Sentry.init anyway, injecting the release is 1) not necessary and 2) has no effect since the `release` option takes precedence.

**Comment by AbhiPrasad** [comment] 2024-11-01 17:25
Closing for clean-up. Please re-open the issue if this still applies. Thanks!

**Closed by AbhiPrasad** 2024-11-01 17:25 UTC

**Comment by benlongo** [comment] 2025-02-28 20:39
There should be a way to opt out of the release injection for service workers. I ran into this with just manually setting up a service worker, no usage of any external packages. Ideally we'd be able to exclude certain files from having the injection happen.

**Comment by lforst** [comment] 2025-03-03 08:51
@benlongo If injection is an issue for you, you can disable injection entirely and simply pass the `release` option to your `Sentry.init()` call.
