### ISSUE TITLE
Is there a plan to support the Sentry Rspack plugin in the future?

### ISSUE THREAD

**Issue by findlay-best-wishes** [getsentry/sentry-javascript-bundler-plugins#574] opened 2024-07-16 07:10 UTC
https://www.rspack.dev/

**Comment by lforst** [comment] 2024-07-16 07:13
Yes but due to the relatively low download numbers it is not a priority for us. We will also likely only start supporting it when it is stable, ie hit semver major 1.

**Comment by findlay-best-wishes** [comment] 2024-07-16 09:12
> Yes but due to the relatively low download numbers it is not a priority for us. We will also likely only start supporting it when it is stable, ie hit semver major 1.

ok, the plugins for webpack are basically compatible with rspack now, it basically works for me.

**Comment by lforst** [comment] 2024-07-16 10:50
Closing as duplicate of https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/407

**Closed by lforst** 2024-07-16 10:50 UTC
Labels: Waiting for: Product Owner
