### ISSUE TITLE
sentry does not consider sourcemaps

### ISSUE THREAD

**Issue by norflin321** [getsentry/sentry-javascript-bundler-plugins#553] opened 2024-06-20 12:09 UTC
- After updating `@sentry/browser` to version `8.10.0` and `@sentry/vite-plugin` to version `2.19.0`, code in issues on sentry website is shown minified. Sourcemaps are uploaded correctly, sourceMappingURL is correct, debugId is correct.
- Literally the same code and the same vite config, but with `@sentry/browser` version `8.9.2` and `@sentry/vite-plugin` version `2.18.0`, works correct!

is this expected behavior? what steps need to be taken to upgrade to new versions?

**Comment by lforst** [comment] 2024-06-20 12:14
Hi, can you share more information? The website, a Sentry event, your setup, ideally a reproduction example? Thanks!

**Comment by Fox32** [comment] 2024-06-27 08:36
Is this fixed by #556?

**Comment by lforst** [comment] 2024-06-27 09:15
@Fox32 Yeah that might very likely be it. @norflin321 @keithgg-carebit @dhenneke (I saw you guys gave this a thumb). Would you mind trying out version `2.20.1` or higher? Thanks!

**Comment by keithgg-carebit** [comment] 2024-06-28 09:51
@lforst looks like that fixed it. I can confirm that the correct number of artifacts are uploaded (with the broken version the number was half), but I haven't checked if the source maps are actually linked properly. 

I'll ping you if that's not the case.

**Closed** 2024-06-28 10:00 UTC
