### ISSUE TITLE
Support monorepo projects similar to nx

### ISSUE THREAD

**Issue by aosnow** [getsentry/sentry-javascript-bundler-plugins#363] opened 2023-08-04 02:24 UTC
## context
Framework: nx v16.4.3
Platform: nodejs v18.17.0
Scaffold: webpack

## request
Currently, debugIdUploadPlugin does not support passing in a parameter named urlPrefix from external sources, which makes it impossible to upload sourcemaps to the corresponding subdirectory level, resulting in situations where "//x.com/a/b.js" cannot match "~/a/b.js.map". Can @sentry/webpack-plugin support passing in the urlPrefix parameter?

**Comment by lforst** [comment] 2023-08-04 07:29
- If you're using the debug ID upload (default) you don't need any paths or filenames to match.
- If you're using the legacy upload option, you can set the `urlPrefix` parameter.

Closing because the functionality should already be there. If there's an issue with any of the options, please provide a small reproduction example and let us know!

**Closed by lforst** 2023-08-04 07:29 UTC
