### ISSUE TITLE
Cannot find module 'webpack' or its corresponding type declarations

### ISSUE THREAD

**Issue by Profesor08** [getsentry/sentry-javascript-bundler-plugins#467] opened 2024-01-31 07:31 UTC
### Environment

`@sentry/vite-plugin@2.10.3`

### Steps to Reproduce

1. install dependency
2. set `skipLibCheck: true` in `tsconfig`
3. run `npx tsc --noEmit`

### Expected Result

To successfully pass all type checks

### Actual Result

There is type error inside

```
> npx tsc --noEmit

node_modules/unplugin/dist/index.d.ts:3:49 - error TS2307: Cannot find module 'webpack' or its corresponding type declarations.

3 import { Compiler, WebpackPluginInstance } from 'webpack';
                                                  ~~~~~~~~~

node_modules/unplugin/dist/index.d.ts:4:45 - error TS2307: Cannot find module 'webpack' or its corresponding type declarations.

4 export { Compiler as WebpackCompiler } from 'webpack';
                                              ~~~~~~~~~

node_modules/webpack-virtual-modules/lib/index.d.ts:1:31 - error TS2307: Cannot find module 'webpack' or its corresponding type declarations.

1 import type { Compiler } from 'webpack';
                                ~~~~~~~~~


Found 3 errors in 2 files.

Errors  Files
     2  node_modules/unplugin/dist/index.d.ts:3
     1  node_modules/webpack-virtual-modules/lib/index.d.ts:1
```

**Comment by lforst** [comment] 2024-01-31 10:49
Duplicate of https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/354

**Closed by lforst** 2024-01-31 10:49 UTC
Labels: Waiting for: Product Owner
